ScilifelabDataCentre/dds_cli

.github/workflows/python-black.yml
cli_code/__init__.py
cli_code/base.py
cli_code/cli_decorators.py
cli_code/data_getter.py
cli_code/data_lister.py
cli_code/data_putter.py
cli_code/data_remover.py
cli_code/dds.py
cli_code/file_encryptor.py
cli_code/file_handler.py
cli_code/file_handler_local.py
cli_code/file_handler_remote.py
cli_code/file_processor.py
cli_code/s3_connector.py
cli_code/user.py
docs/source/conf.py
pyproject.toml
setup.py

* Added a `pyproject.toml` config file to set the Black line length to 120
* Re-ran Black with the new line length, also with the latest version of Black
* Added a GitHub Actions CI workflow to test that the black formatting is valid
I started from `master` so the PR picked up your merge commits from previous `dev`->`master` PRs. They should be harmless, but let me know if you'd prefer me to rebase to remove them.

Black update

---

.github/workflows/deploy-workflow.yml
.github/workflows/python-black.yml
cli_code/__init__.py
cli_code/base.py
cli_code/cli_decorators.py
cli_code/data_getter.py
cli_code/data_lister.py
cli_code/data_putter.py
cli_code/data_remover.py
cli_code/dds.py
cli_code/file_encryptor.py
cli_code/file_handler.py
cli_code/file_handler_local.py
cli_code/file_handler_remote.py
cli_code/file_processor.py
cli_code/s3_connector.py
cli_code/user.py
docs/source/conf.py
pyproject.toml
requirements.txt
setup.py

Information should be saved to the error log.

error log fix & black

---

dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/data_putter.py

The project size is now updated after all files have been uploaded. This is due to the deadlock issue occurring when multiple requests try to update the same point in the db at the same time. Looking into handling this with queues in flask instead.

Changed handling of the project size update

---

dds_cli/__main__.py
dds_cli/base.py
dds_cli/data_getter.py
dds_cli/data_lister.py
dds_cli/data_putter.py
dds_cli/data_remover.py
dds_cli/file_handler.py
dds_cli/file_handler_local.py
dds_cli/file_handler_remote.py
dds_cli/user.py

I hit some weird bugs when testing the web uploads where stuff would fail (I could see the message in the log), but the web front end would show a success message. Looking in the cli code, I can see lots of system exit calls with status `0`. Exit code `0` is good and means a normal exit. Anything other than 0 means something is wrong. So, I switched all of the bad ones I could find to `1`.
Spotted a couple other bits that I think need fixing that I saw on this speed read. I've put them in #78 so that they don't get lost when this PR is merged.

Fixed exit codes

---

dds_cli/__main__.py
dds_cli/base.py

Because no command line tool is complete without an ascii header 😆

Add fancy ascii header

---

dds_cli/base.py
dds_cli/data_lister.py

CLI no longer recognizing the project ID field in the config file.

Project config cleanup

---

dds_cli/__main__.py
dds_cli/base.py
dds_cli/cli_decorators.py
dds_cli/data_getter.py
dds_cli/data_lister.py
dds_cli/data_putter.py
dds_cli/data_remover.py
dds_cli/file_handler.py
dds_cli/file_handler_local.py
dds_cli/file_handler_remote.py
dds_cli/user.py
dds_cli/utils.py

Fixed glitchy  progress bars. This was done in the way that was suggested in #129 -- by creating a `Console` object in `utils.py` which is then reused by all files writing output and by the progress bars.

Fix glitchy progress bars

---

dds_cli/file_encryptor.py

Add log message about successful checksum verification

---

dds_cli/cli_decorators.py
dds_cli/file_handler.py
dds_cli/file_handler_local.py

Added warning about non existent files in when using `-spf` option of `dds put`. Should close #92.

Report files which are non existent when using `-spf`

---

dds_cli/__main__.py
dds_cli/data_lister.py

Added `--tree` option to `dds ls` for showing the whole file tree in the remote. Should close #111. Showing file sizes depends on merging https://github.com/ScilifelabDataCentre/dds_web/pull/547.
The method uses two tree walks, one for constructing the file tree and computing the maximum indentation needed, and one for the construction of the `rich` tree. These could however be coalesced into one by updating the subtrees recursively if one finds that the maximum indentation needed for one subtree is greater than the other subtrees. I didn't implement it this way for readability (and ease of implementation) reasons. If it happens that this command is slow with the current implementation however, the improved speed of using one tree walk could perhaps justify the added complexity. …

Add `--tree` option to `dds ls`

---

.gitignore
tests/tools/tools_for_testing.py

file required by `pytest` should've been an exception in the gitgnore

Tools for testing

---

dds_cli/__main__.py
dds_cli/data_lister.py
tests/test_list.py

Sorry for a very messy PR. Most of the changes are moving around the methods inside the data lister to adhere to the standard we have in most other classes.

dds ls --json

---

dds_cli/directory.py
dds_cli/file_compressor.py
dds_cli/file_encryptor.py
dds_cli/file_handler.py
dds_cli/file_handler_local.py
dds_cli/file_handler_remote.py

Removing all os.umask() occurrences since it doesn't seems to do anything. 
Please test this yourselves though and let me know if something regarding reading or writing breaks for you.

Removed all umask

---

dds_cli/user.py

Closes https://github.com/ScilifelabDataCentre/dds_web/issues/746

dds session typo fix

---

dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/account_manager.py

Displays a logged in user's name, username, role and associated emails

Add dds user info command

---

dds_cli/account_manager.py
dds_cli/data_lister.py
dds_cli/project_status.py
tests/test_add_user.py
tests/test_list.py

This will match the web changes in https://github.com/ScilifelabDataCentre/dds_web/pull/771 after  https://github.com/MatthiasZepper/dds_web/pull/8

changed params and json

---

dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/account_manager.py

Added the following commands with email as required argument.
* dds user activate
* dds user deactivate

Add user activate/deactivate commands

---

dds_cli/__main__.py
requirements.txt

Add rich-cick cli help formatting

---

dds_cli/__main__.py
dds_cli/account_manager.py
dds_cli/base.py
dds_cli/cli_decorators.py
dds_cli/data_remover.py
dds_cli/project_status.py

Changed some outputs to stdout so that it can be more easily parsed when dds is called from another program.
- Used the `--no-prompt` option to decide between rich and json outputs when running `dds put`.

Change some outputs to stdout

---

CHANGELOG.md
dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/account_manager.py

This PR adds the command to match [this PR in the web](https://github.com/ScilifelabDataCentre/dds_web/pull/885). 
Implements at least a start of what is described in [this comment](https://github.com/ScilifelabDataCentre/dds_web/issues/876#issuecomment-1040086353)

dds project access fix

---

dds_cli/__main__.py
requirements.txt

Just wrapped up a new usage pattern for `rich-click`. Laptop battery about to die, so will push the release tomorrow, but this PR will then be ready for the new syntax.
Before submitting a pr:

New simpler rich-click usage

---

CHANGELOG.md
dds_cli/__main__.py
dds_cli/project_creator.py

change to non-sensitive

---

CHANGELOG.md
dds_cli/__init__.py
dds_cli/auth.py
dds_cli/exceptions.py
dds_cli/user.py
dds_cli/utils.py
requirements.txt
tests/test_utils.py

Token expiration

---

setup.py

New version

---

setup.py

getting up to speed with the weird versions

---

setup.py

version change

---

setup.py

Version change - remove dev from end

---

setup.py

New version, hopefully last before testing

---

README.md
setup.py

new version and updated readme

---

README.md
setup.py

Incorrect information in readme

---

.github/pull_request_template.md
setup.py

change in version

---

README.md

Readme was incorrect

---

docs/index.rst

add pypi link

---

requirements.txt

pandas and numpy removed

---

dds_cli/__main__.py

Update show-history option

---

dds_cli/__main__.py
dds_cli/auth.py

This patch removes message duplication when the user logs out.

Remove message duplication

---

dds_cli/__main__.py
dds_cli/auth.py

change previous merged PR after finding duplicate

---

dds_cli/auth.py

unused boolean return

---

docs/auth.rst
docs/project.rst
docs/user.rst
docs/web.rst

update docs with comments from testing

---

.gitignore

add windows

---

dds_cli/__main__.py

Fix the form of one verb.
- [-] Note in the CHANGELOG

Compressed -> compresses

---

setup.py

bump cli version

---

CHANGELOG.md
dds_cli/s3_connector.py

minor change for the cli to work with minio in dev mode

---

CHANGELOG.md
dds_cli/s3_connector.py

Reverts ScilifelabDataCentre/dds_cli#335

Revert "minor change for the cli to work with minio in dev mode"

---

CHANGELOG.md
dds_cli/__init__.py

Should be combined with pr [#933](https://github.com/ScilifelabDataCentre/dds_web/pull/993) from dds_web.

Add support for zero-conf dev environment to the cli

---

CHANGELOG.md
dds_cli/__init__.py

Increase timeout to 30

---

dds_cli/account_manager.py
dds_cli/data_getter.py
dds_cli/data_lister.py
dds_cli/file_handler_remote.py
dds_cli/project_creator.py
dds_cli/project_status.py
tests/test_add_user.py
tests/test_list.py

Add timeouts to requests

---

dds_cli/account_manager.py

Fix `dds user delete --self` bug

---

dds_cli/directory.py

f string to fix bug

---

dds_cli/__main__.py
dds_cli/utils.py

Changed proceed_deletion check

---

CHANGELOG.md
dds_cli/__main__.py

Replace the default help messages of Click

---

dds_cli/account_manager.py

This is to match the web PR: 
https://github.com/ScilifelabDataCentre/dds_web/pull/1026
Fixed due to confusion among testers. 

fix error messages

---

dds_cli/auth.py

This removes duplicated file permission checks.

Remove duplicate file permission checks

---

dds_cli/custom_decorators.py
dds_cli/directory.py
dds_cli/file_compressor.py
dds_cli/file_handler_remote.py
dds_cli/options.py
dds_cli/project_status.py
dds_cli/utils.py

Some code cleanup:
* Avoid mutable function argument
* Use `list(data)` instead of `[x for x in data]`
* Unused imports
* Avoid redefining built-ins
* Use snake_case instead of camelCase
* Use f-strings instead of `.format` in some cases
- [-] Note in the CHANGELOG

Code cleanup

---

dds_cli/project_creator.py

**Test with:** https://github.com/ScilifelabDataCentre/dds_web/pull/1066

Warning and confirmation prompt when creating projects in unit without 3 unit admin

---

CHANGELOG.md
dds_cli/__main__.py

Definitely needs some improvement later but good enough for now. 

allow delete of both file and folder

---

dds_cli/user.py

Check if token exists

---

dds_cli/__main__.py

Can be merged when https://github.com/ScilifelabDataCentre/dds_web/pull/1061 is ready.

change to 7 days

---

dds_cli/account_manager.py

Fix error message

---

.github/workflows/deploy-workflow.yml

Small indentation fix on the action.

Fix indentation on deploy action.yml

---

tests/test_list.py

get_required_in_response() is failing when ['units', 'keys']  are not returned and I am not yet sure how to mock this

test for unit ls

---

.github/workflows/deploy-workflow.yml

This patch adds Linux to deploy-workflow.yml.

Add Linux to deploy-workflow.yml

---

README.md

Change example in readme

---

dds_cli/__main__.py
docs/index.rst

Update docs according to tester feedback

---

dds_cli/__main__.py
dds_cli/base.py
dds_cli/data_getter.py
dds_cli/data_lister.py
dds_cli/data_remover.py
dds_cli/exceptions.py
dds_cli/file_handler_local.py
dds_cli/file_handler_remote.py
dds_cli/project_creator.py
dds_cli/project_status.py
dds_cli/s3_connector.py
dds_cli/user.py
dds_cli/utils.py

Base main connection error

---

dds_cli/account_manager.py

catch connectionerror in account manager

---

docs/installation.rst

Fix bianca docs

---

docs/installation.rst

fix invalid characters

---

docs/installation.rst

Fix of docs

---

docs/installation.rst

Instructions on executables

---

docs/installation.rst

Info on executables in docs

---

CHANGELOG.md
dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/motd_manager.py

Command for adding a new MOTD.
Test with https://github.com/ScilifelabDataCentre/dds_web/pull/1136

Add MOTD command

---

CHANGELOG.md
dds_cli/__main__.py

Add docstring about "Please reauth" before delivery to avoid delivery being cancelled

---

docs/index.rst

remove 'currently minimal'

---

dds_cli/account_manager.py
dds_cli/utils.py

Refactor requests in account_manager.py

---

CHANGELOG.md
dds_cli/__main__.py

Update help message for PI option

---

.github/workflows/deploy-ghp.yml
CHANGELOG.md
dds_cli/__main__.py
requirements-dev.txt

This PR is so that the documentation is fixed and displays the correct information about the PI option.

Update help message and slight refactoring

---

dds_cli/file_handler_local.py

Replace "requests.get" in "file_handler_local.py" with the "request_get" function from "utils.py"

---

dds_cli/project_status.py

Replace "requests.get" in "project_status.py" with the "request_get" function from "utils.py"

---

dds_cli/user.py

Replace "requests.get" in "user.py" with the "request_get" function from "utils.py"

---

dds_cli/account_manager.py
dds_cli/base.py
dds_cli/data_lister.py
dds_cli/file_handler_local.py
dds_cli/file_handler_remote.py
dds_cli/project_status.py
dds_cli/s3_connector.py
dds_cli/unit_manager.py
dds_cli/user.py
dds_cli/utils.py

Rename utils.py: requests_get() and adapt all calls

---

dds_cli/data_getter.py
dds_cli/utils.py

Replace "requests.put" in "data_getter.py" with the "perform_request" function from "utils.py"

---

dds_cli/data_putter.py
dds_cli/utils.py

Replace "requests.put/post" in "data_putter.py" with the "perform_request" function from "utils.py"

---

dds_cli/motd_manager.py
dds_cli/utils.py

This requires a follow up task: https://scilifelab.atlassian.net/browse/DDS-1270?atlOrigin=eyJpIjoiY2EwY2I5NDNkM2RmNGQ4OWEzODMyNmQ2NWM4ZGZhYTciLCJwIjoiaiJ9

Message of the day post request replaced

---

dds_cli/project_status.py

Replace post request with common function in project_status.py

---

dds_cli/project_creator.py

This requires the following follow up task: https://scilifelab.atlassian.net/browse/DDS-1271?atlOrigin=eyJpIjoiMmQ4NGFlYmRhMDdkNDc1NDgxMzk2MTBlYzRmMmUzZjEiLCJwIjoiaiJ9

Refactor post request from project_creator

---

dds_cli/utils.py
tests/requirements-test.txt
tests/test_empty.py
tests/test_utils.py

This patch updates the error messages for project creation.
Fixes DDS-1271.

Project Creation Error

---

.github/pull_request_template.md

Since we're slowly but surely adding unit tests to the CLI again, we should keep track of the code coverage.
Fixes X

Add codecov to repo

---

.github/workflows/python-app.yml
README.md
dds_cli/utils.py

I made a mistake in the previous codecov setup. 
Fixes X

Codecov fixes

---

dds_cli/utils.py
tests/test_utils.py

Improvement in error handling for "dds motd add"
Works together with https://github.com/ScilifelabDataCentre/dds_web/pull/1167
Fixes DDS-1270

handle motd add error

---

dds_cli/utils.py
tests/requirements-test.txt
tests/test_utils.py

This patch adds unit tests.
Part of DDS-1279

Unit tests

---

dds_cli/auth.py
dds_cli/user.py
dds_cli/utils.py
tests/test_utils.py

This patch adds the version header.
Fixes DDS-1259.

Version Header

---

.github/workflows/python-app.yml
dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/motd_manager.py
tests/requirements-test.txt
tests/test_utils.py

Display in cli. 
Works with https://github.com/ScilifelabDataCentre/dds_web/pull/1198

Display MOTD in cli

---

codecov.yml

codecov range changed to 60-90

---

README.md

Link do documentation and backend

---

CHANGELOG.md
dds_cli/base.py
dds_cli/data_getter.py
dds_cli/data_putter.py
dds_cli/data_remover.py

This is an add-on to https://github.com/ScilifelabDataCentre/dds_cli/pull/525 - some refactoring.
Merge 525 first and then rebase this. 
Should be tested with https://github.com/ScilifelabDataCentre/dds_web/pull/1266 
Fixes DDS-1332

Set project as busy during download (2)

---

.github/pull_request_template.md
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-workflow.yml
.github/workflows/prettier.yml
.github/workflows/python-app.yml
.github/workflows/python-black.yml
README.md
SECURITY.md
docs/_static/custom.css

This PR edits the PR template to what I'm currently using. The previous one caused confusion and this one is hopefully easier to follow and fill in. This also adds the Prettier code scanning.

Update pr template

---

CHANGELOG.md
dds_cli/base.py

Add project public_id to end of the temp directory created when uploading or downloading of data. This will allow users to deliver to two different projects if deliveries initiated at the same time
- [x ] Fixes [(https://scilifelab.atlassian.net/browse/DDS-1341) / DDS-1341]

Add project public_id to the dds dir name

---

CHANGELOG.md
dds_cli/__main__.py
dds_cli/maintenance_manager.py
tests/test_maintenance_manager.py

Add tests for maintenance_manager and a fix for wrong error raised

Add tests for maintenance_manager and an error fix

---

dds_cli/data_getter.py
docs/index.rst

Avoid researchers contacting us at Data Centre by informing them that they should contact support instead.

Inform users of contacting "support" and not "Data Centre"

---

tests/test_file_encryptor.py

It'll most likely take more effort than it's worth to add tests for the entire cli at this point, but some crucial and easily functions should be tested. The PR adds tests the encryptor and decryptor and makes sure that they generate the correct keys.

Dds 1360 file encryptor py generate shared key

---

CHANGELOG.md
dds_cli/__init__.py
dds_cli/__main__.py
dds_cli/account_manager.py

Add a command `dds user ls --invites` that will use the new endpoint in #1294 in dds_web.
Implements Jira issue DDS-1354.

Command for listing invites

---

dds_cli/file_encryptor.py
tests/test_file_encryptor.py

Adds test for file_encryptor static functions.

Test public_to_hex

---

tests/test_file_encryptor.py

Adds tests for file_encryptor.

Test get_public_component_hex

---

tests/test_file_compressor.py

Test decompress_filechunks

---

dds_cli/__main__.py

To avoid confusion: Change from
```bash
︵ 
︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
︶  (  ) ) (    https://delivery.scilifelab.se/ 
︶ (  )    Version 2.1.1 
︶
```
to
```bash
︵ 
︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
︶  (  ) ) (    https://delivery.scilifelab.se/ 
︶ (  )    CLI Version 2.1.1 
︶
```
Decided after discussion with @valyo and checking with the users.

Change from "Version" to "CLI Version" in CLI printout

---

.github/pull_request_template.md

Changed this PR template slightly  regarding version update etc.

Alter item in PR template for clarity

---

CHANGELOG.md
dds_cli/__main__.py
dds_cli/utils.py

Currently if the user does not specify either of the options, it just returns a message saying “no data specified” which seems to confuse the users and result in support tickets.
Add a check for this and inform them in the CLI of the different options.

Check that `dds data get` is used with either `--get-all` or `--source` and display appropriate message

---

docs/index.rst

Same reason as https://github.com/ScilifelabDataCentre/dds_web/pull/1318.
Improve instructions to clarify.

Update "how do i get my user account" section

---

.github/workflows/rich-codex.yml
README.md

Update readme and add action for rich-codex.

new yml for rich codex

---

img/dds-help.svg

Generate new screengrabs with rich-codex

---

.github/workflows/docs-github-pages-cli.yml
.github/workflows/lint-black-cli.yml
.github/workflows/lint-prettier-cli.yml
.github/workflows/release-cli.yml
.github/workflows/rich-codex-cli.yml

> **Before submitting the PR**
>
> - Fill in and tick fields
> - _Remove all rows_ that are not relevant for the current PR
>   - Revelant option missing? Add it as an item and add a PR comment informing that the new option should be included into this template.
>
- Fixes an issue in GitHub / Jira:
- Tests
- Trivy:

Add descriptions of current code scanning tools

---

.gitignore
CHANGELOG.md
docs/index.rst
docs/motd.rst
docs/testing.rst

We need instructions on how to test the DDS via the test / dev instance. So far I have sent out instructions to the different units via email, but this is error prone and I risk missing information or confusing people. It also means that I have the important information, but no one else within DC does. This risks complications and additional support tickets. 
This PR adds a testing instruction page to the documentation. When a new unit is created in the DDS test instance, I will inform them of this in an email and link to this instruction page. 
_Add information on additional changes required for the PR changes to work, both locally and in the deployments._
> E.g. Does the deployment setup need anything for this to work?
- Rebase / Update / Merge _from_ base …

Add test instance instructions

---

.github/workflows/trivy-cli.yml

Changes the scan from IaC (config files) to filesystem. 
_X_
- Blocking PRs
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
Run `npx prettier --write .` locally to execute formatting.
- **Tests**: Pytest to verify that functionality works as expected.
- **TestPyPi**: Build CLI and publish to TestPyPi in order to verify before release.
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
- **Trivy**: Security scanner
- **Snyk**: Security scanner

Update trivy workflow to scan code and not IaC

---

.github/workflows/lint-black-cli.yml
.github/workflows/lint-prettier-cli.yml
.github/workflows/pytest-cli.yml
.github/workflows/release-cli.yml
.github/workflows/test-pypi-cli.yml

1. **Description:** Some of the actions are giving warning messages. This bumps some of the action versions.
2. **Jira task / GitHub issue:** DDS-1510
3. **How to test:** _X_
- Blocking PRs
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
Run `npx prettier --write .` locally to execute formatting.
- …

Update versions of github action due to warnings

---

SPRINTLOG.md
dds_cli/file_handler_remote.py

1. **Description:** While using the log file option, the DDS is still saving a lot of information which makes the logs a lot less readable. I've removed a few of the instances that save a lot of it. 
2. **Jira task / GitHub issue:** DDS-1524
- Blocking PRs
Run …

Remove debug level logging

---

SPRINTLOG.md
docs/testing.rst

1. **Description:** This updates the instructions for testing since the current instructions do not include how to define environment variables in Windows. 
2. **Jira task / GitHub issue:** DDS-1528
3. **How to test:** Use the specified commands in Windows cmd and PowerShell. (Already tested)
- Blocking PRs
- **Prettier**: General code …

Update instructions for setting environment variable

---

SPRINTLOG.md
docs/index.rst
docs/password.rst

1. **Description:** Added recommendation to use Bitwarden. 
3. **How to test:** 
1. Go into the `docs` directory
2. Run `make clean html`
3. Run `open _build/html/password.html`
4. Check that it looks ok and for spelling errors or missing/incorrect information.
5. **Type of change:** [_Check the relevant boxes in the section below_](#what-type-of-changes-does-the-pr-contain)
6. **Add docstrings and comments to code**, _even if_ you personally think it's obvious.
- Blocking PRs
Run `black .` …

Dds 1445 instructions password management

---

SPRINTLOG.md
dds_cli/__init__.py

1. **Description:** _Add a summary of the changes in this PR and the related issue._
- Blocking PRs …

Change url to dckube3

---

docs/testing.rst

1. **Description:** _Add a summary of the changes in this PR and the related issue._
- Blocking PRs …

Update docs to show dckube3

---

tests/requirements-test.txt

1. **Description:** _Add a summary of the changes in this PR and the related issue._
- Blocking PRs …

Bump werkzeug (only used in tests)

---

.github/workflows/release-cli.yml

1. **Description:** Not sure if this actually helps but it could. Bumping one of the actions for python to the latest version. 
2. **Jira task / GitHub issue:** DDS-1529
- Blocking PRs
- **Pylint**: Python code linter. …

Fix pdf documentation

---

SPRINTLOG.md
requirements.txt

1. **Description:** _Add a summary of the changes in this PR and the related issue._
- Blocking PRs …

Pyyaml bump to 6.0.1

---

SPRINTLOG.md
dds_cli/file_encryptor.py

Change "Checksum verification successful. File integrity verified." info log to debug

---

SPRINTLOG.md
requirements.txt

update cryptography package for cve

---

requirements.txt

update jwcrypto to address cve

---

CHANGELOG.rst

Patch changelog due to undocumented update

---

SPRINTLOG.md
requirements.txt

Update requests to solve CVE

---

dds_cli/__init__.py

URL changed

---

.github/workflows/docs-github-pages-cli.yml
SPRINTLOG.md
requirements-dev.txt

GitHub pages action fail fixed

---

SPRINTLOG.md
docs/index.rst
docs/installation.rst
docs/testing.rst

Update the testing instance related to docs to be more findable
and also accurate. 
_Link to the github issue or add the Jira task ID here._
What _type of change(s)_ does the PR contain?
**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**
_Check the boxes when the specified checks have passed._
**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md).**

DDS-2023 update test docs

---

SPRINTLOG.md
requirements-dev.txt

Unpin pyinstaller

---

.github/CODEOWNERS
SPRINTLOG.md

CODEOWNERS file

---

dds_cli/__main__.py

Minor docs fix

---

.github/workflows/pytest-cli.yml
.github/workflows/release-cli.yml
SPRINTLOG.md
WINDOWS.md
docs/installation.rst
requirements.txt
setup.py
tests/requirements-test.txt

Bump python version in client

---

SPRINTLOG.md

Move version row to correct sprint

---

SPRINTLOG.md
dds_cli/data_remover.py
tests/test_data_remover.py

- The data remover function handles the new message response from the …

Adapted client remove all conrents message according to Queuing POC

---

.github/workflows/release-cli.yml
SPRINTLOG.md

Ubuntu latest has relatively recently changed to 24.04, so we added the …

Add ubuntu 20.04 as an executable again

---

.github/workflows/release-cli.yml
SPRINTLOG.md

The build of the documentation failed during the release of v2.10.0, which …

Update action upload-artifact to v4 -- v3 deprecated

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

**Add a summary here**: What does this PR add/change and why?
**Is this a …

Add Release Drafter Github Action

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
SPRINTLOG.md

This PR adds the Github action which creates a release draft when there's a …

New Github Action for automatically generating release draft: Release Drafter

---

.github/release-drafter.yml
SPRINTLOG.md

Atm, the release-drafter adds the "Changes" title to the top of the release …

Remove "Changes" title from release drafts

---

.github/release-drafter.yml
SPRINTLOG.md

This structures the config file for the Release Drafter, changes the labels …

Change Release Drafter config structure

---

.github/release-drafter.yml

**Add a summary here**: What does this PR add/change and why?
**Is this a …

Labels in version resolver in Release Drafter

---

.github/release-drafter.yml

When a new release template is created or updated, the current target …

Change release template target to master

---

docs/installation.rst

Updates broken links to Uppmax documentation.
**Is this a GitHub issue?** --> Add the link to the github issue
**Is this from a Jira task?** --> If your branch does not contain info regarding the Jira task ID, put it here.
`type: docs` Documentation only change.
**Make sure that the following checks/actions have passed.**
- **Black**
- **Prettier**
- **Pylint**
- **Yamllint**
- **Tests**
- **CodeQL**
- **Trivy**
- **Snyk**
- **TestPyPI**
If an action does not pass and you need help with how to solve it, enter edit mode of this PR template or go to the [PR template](../.github/pull_request_template.md).

Update installation.rst with correct Uppmax links

---

.github/release-drafter.yml

**Add a summary here**: What does this PR add/change and why?
**Is this a …

Remove commitish -- Release Drafter is not picking up changes
