pyproject.toml
I was a bit ahead of myself in adding Python 3.9 for the Black style yet: https://github.com/ScilifelabDataCentre/DS_CLI/runs/2501903983#step:4:11
=> Black doesn't support Python 3.9 yet

.github/workflows/deploy-workflow.yml
This workflow automatically builds and publishes the package to the Python Package Index (PyPI) when a new release is created on GitHub.
You'll need to create a repository secret with the name `pypi_password`. See https://github.com/pypa/gh-action-pypi-publish
=> Added workflow to automatically publish to PyPI on GH release

README.md, setup.py
I noticed a copy+paste typo in the `dev` installation command that I added last night. Fixed here.
I also rephrased some of the text now that I came back to it with fresh eyes.
=> Readme typo in dev installation command

dds_cli/base.py, dds_cli/cli_decorators.py, dds_cli/data_putter.py, dds_cli/file_encryptor.py, dds_cli/s3_connector.py
To be taken together with https://github.com/ScilifelabDataCentre/dds_web/pull/465 on `dds_web`.
Instead of continuing execution if the server does not return the required s3 connection details, `assert` it and raise an exception if something is wrong.
Together with the web PR, I now get this:
```python
Traceback (most recent call last):
File "/Users/ewels/miniconda3/envs/py3/bin/dds", line 33, in <module>
sys.exit(load_entry_point('dds-cli', 'console_scripts', 'dds')())
File "/Users/ewels/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/Users/ewels/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File …
```
=> Don't silently fail and try to carry on if s3 connection response fails

dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/base.py, dds_cli/data_lister.py, requirements.txt
Work in progress, trying to make the `dds ls` command easier to use (from my perspective) and a bit fancier.
Will add to this list as I go and mark as ready to review when I think the PR has enough :)
* Clean up command line flags
* Positional only for project and folder (reversed order)
* `--projects` removed and inferred by lack of specified `project`
* More cli help text
* Instead of warning if there is a lot of output, automatically page the output
* Use the [`rich` console pager](https://rich.readthedocs.io/en/stable/console.html#paging)
* Base the decision on the height of the user's terminal, not an arbitrary count
* Non-interactive usage (eg. piping / redirecting to a file) will still have normal behaviour
* Prompt for a project to view files for
* After printing table of …
=> `dds ls` usability improvements

dds_cli/__main__.py
`dds ls` was displaying the message `Would you like to view files within a directory? Leave blank to exit." even if there are no folders in the project. Add check for folders before displaying message.
=> Remove redundant message in `dds ls`

dds_cli/__main__.py, dds_cli/cli_decorators.py, dds_cli/data_remover.py
Replaced call to the removed `warn_if_many` function from `data_lister.py` with pagination of tables if they are too long.  Should close #128.
=> Remove call to deprecated `warn_if_many`

dds_cli/exceptions.py
Shows the actual error message.
=> Show human-readable error message when parsing the JSON-config fails

dds_cli/base.py, dds_cli/cli_decorators.py, dds_cli/data_putter.py, dds_cli/file_handler.py
Errors are now logged more or less directly after failure upon exiting the `verify_proceed` wrapper. Since multiple threads could be appending lines to the log, I changed the format of the log so that each line is valid json but the entire file is unfortunately not. Parsing should be easy enough just reading line by line.
I ran 32 threads (on my laptop though) and multiple threads appending to the file did not cause any issues, but I'm not sure it's a recommended praxis. Safer would be to have a single thread taking care of the logging or keeping a global lock variable in the owning class perhaps.
However, I think there might be better ways of making sure that the bucket and database is in sync which seems to be the ultimate goal of this log.
=> Log errors for upload directly

dds_cli/utils.py
Fixed bug that would result in trailing 0 being trimmed for exactly 10 and 100. 
Partly solves [issue 671 of the web](https://github.com/ScilifelabDataCentre/dds_web/issues/671).
=> Bug fix regarding web/issue671

dds_cli/__main__.py, dds_cli/base.py, dds_cli/exceptions.py, dds_cli/user.py
- Made username argument not required as this is only required when the session token needs to be renewed. 
- Instead made project argument required where it actually is, which removed the need for the __verify_input method.
- Got rid of the `MissingCredentialsException` class as the `AuthenticationError` is sufficient.
=> Username not required

dds_cli/__main__.py, dds_cli/account_adder.py, dds_cli/auth.py, dds_cli/base.py, dds_cli/data_getter.py, dds_cli/data_lister.py, dds_cli/data_putter.py, dds_cli/data_remover.py, dds_cli/exceptions.py, dds_cli/file_handler_local.py, dds_cli/file_handler_remote.py, dds_cli/project_creator.py, dds_cli/user.py, dds_cli/utils.py, demo/creds_get.json, demo/creds_put.json
- Implemented the `--no-prompt` flag to fail rather than ask for missing arguments.
- Renamed Session to Auth everywhere
- New subcommands: `dds auth login`, `dds auth logout` and `dds auth info`.
- Removed some demo data.
- Tiny improvements on printing logic
=> No Prompt and more

dds_cli/__main__.py, dds_cli/base.py, dds_cli/cli_decorators.py, dds_cli/data_getter.py, dds_cli/data_putter.py, dds_cli/data_remover.py, dds_cli/s3_connector.py
1. Switch back rich logging level to info (unless verbose)
2. Make progress bars log to stderr instead of stdout
3. Move some log statements from info to debug if they’re normally not needed for the end user (This is of course a subjective choice)
This will re-enable the messages printed to users for `dds auth info` and `dds ls` which are otherwise muted if the level is set to warning.
=> Logging vs progressbars

dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/account_manager.py, dds_cli/user.py, dds_cli/utils.py, tests/test_add_user.py
This PR comprises the necessary changes to the CLI to address [issue 703](https://github.com/ScilifelabDataCentre/dds_web/issues/703) from the web: 
- Newly introduced the feature to delete user accounts in the CLI.
- To delete the own account, one would need to enter `dds user delete --self`
-  To delete any other account (given sufficient administrative privileges), one would need to specify `dds user delete EMAIL`
- The former `dds add-user`  command is now `dds user add` and its former option `--email` is now its argument.
- Created an `utils.email_validator` function that will employ a simple Regex to check if a valid email address was entered before dispatching the API call since a failed marshmallow validation doesn't seem to be properly handled in the CLI so far.
=> Issue703: Introduce dds user command group

dds_cli/data_lister.py, dds_cli/project_status.py, dds_cli/user.py, requirements.txt, tests/test_list.py
Converts the timestamps in UTC received from dds_web to timestamps in the local timezone on the system where the CLI is installed. Should work on UNIX-like and Windows systems, although not tested for Windows.
=> Add timestamp localization by using local timezone info

dds_cli/exceptions.py, dds_cli/file_handler_local.py, dds_cli/file_handler_remote.py, dds_cli/utils.py
Addresses [issue 769 of the web](https://github.com/ScilifelabDataCentre/dds_web/issues/769)
Added obfuscation to the _Name_in_Bucket_ parameter. Now neither the file's name nor the file's path can be reconstructed from the object's name in the bucket. 
Because the file's path is now also a UUID, exceedance of the 1024 bytes maximum length never happens. Thus, the corresponding exception was removed.
No changes to the web are required for this.
=> Added obfuscation to the Name_in_Bucket parameter (issue 769 of web)

dds_cli/__main__.py
Now that @talavis added storage location for flask limiter in production (#774, redis), I tested it out and got a huge error message when the API reached the limit. This PR caches the ApiResponseError in `__main__` so that the messages are actually understandable.
Noticed though that the resulting error message displays two times, plus a `NoneType: None` thing. Don't know where that row  or where the second row of errors comes from.
=> displays readable message and not an exception

dds_cli/__main__.py
I changed the default maximum width for `rich-click` to be the full width of the terminal.
This PR customises the package to limit the width to 100 characters (or the width of the terminal if less than that).
Personally I think it looks better for `dds` as the majority (all?) of the help messages fit within this width.
The end result is the same as when I originally added the package, before I changed the default.
=> Click help: max 100 chrs wide

CHANGELOG.md, dds_cli/__main__.py, dds_cli/user.py
=> Show logged in user in header

CHANGELOG.md, dds_cli/__main__.py, dds_cli/account_manager.py, dds_cli/options.py, dds_cli/project_status.py, tests/test_add_user.py
Before submitting a pr:
Introduced a `--no-mail` flag in the CLI respectively a `send_email: True/False` json parameter to fix [issue 924](https://github.com/scilifelabdatacentre/dds_web/issues/924) ([#253](https://github.com/ScilifelabDataCentre/dds_cli/pull/253))
=> Issue924 no mail flag

dds_cli/project_creator.py
The API can send different error messages. This patch prints the error message that the API sends.
Before submitting a pr:
=> Print error message

CHANGELOG.md, dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/account_manager.py, tests/test_add_user.py
=> added unit and changed url

CHANGELOG.md, requirements.txt
The DDS cli has a custom exception type based on a click exception. This doesn't provide a click `ctx` context object, as is provided when the exception is generated from the command line. As such, we get an ugly traceback.
Version 1.2.1 of rich-click solves this by making the `ctx` object optional. This PR updates the requirements to require at least that version of rich-cick.
---
=> rich-click v1.2.1 at least, handle exception problems

CHANGELOG.md, dds_cli/base.py
Treat "already uploaded" separately from other errors.
Instead of
```
Errors occurred during upload.
If you wish to retry the upload, re-run the `dds data put` command again, specifying the same options as you did now. To also overwrite the files that were uploaded, also add the `--overwrite` flag at the end of the command.
See /code/DataDelivery_2022-03-04_10-52-47/logs/dds_failed_delivery.txt for more information.
```
The output is now
```
Upload completed!
5 files were already uploaded.
```
Fixes #300.
=> Treat "already uploaded" differently from other upload errors

CHANGELOG.md, dds_cli/__main__.py
Makes the URL in the logo change depending on what `DDS_CLI_ENV` is set to.
```
root@1105fd8508d9:/code# dds auth info
︵
︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
︶  (  ) ) (    http://dds_backend:5000/
︶ (  )    Version 0.0.10
︶
Current user: unituser_1
INFO     ✅  Token is OK! ✅
INFO     ✅  Token will expire in 1 day 23 hours 49 minutes! ✅
```
=> Change url based on what env we are using

CHANGELOG.md, dds_cli/__main__.py
Give correct response when there are failed emails during validation
With https://github.com/ScilifelabDataCentre/dds_web/pull/1014:
```
$ dds project create -t t -d d -pi p --researcher asd@asd --owner asd@adsad
︵
︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
︶  (  ) ) (    http://dds_backend:5000/
︶ (  )    Version 0.0.10
︶
Current user: unituser_1
Project created with id: someunit00023
Error for asd@adsad: {'email': ['Not a valid email address.']}
Error for asd@asd: {'email': ['Not a valid email address.']}
```
With this pr:
```
$ dds project create -t t -d d -pi p --researcher asd@asd --owner asd@adsad
︵
︵ (  )   ︵
(  ) ) (  (  )   SciLifeLab Data Delivery System
︶  (  ) ) (    http://dds_backend:5000/
︶ (  )    Version 0.0.10
︶
Current user: unituser_1
Project created …
```
=> Print error message when there are failed emails during project creation

dds_cli/exceptions.py
When you try to use the `dds auth login` function more than 10 times per hour:
```
INFO     Attempting to renew the session token                    
DDS username: superadmin
DDS password: 
ERROR    API returned an error: Too many authentication requests  
in one hour                                              
NoneType: None                                           
ERROR    API returned an error: Too many authentication requests  
in one hour          
```
With this PR (there was a log line in one of the custom exceptions):
```
INFO     Attempting to renew the session token                    
DDS username: superadmin
DDS password: 
ERROR    API returned an error: Too many authentication requests  
in one hour      
```
- [ - ] Rebase/merge …
=> remove duplicate message after response error

CHANGELOG.md, dds_cli/__main__.py, dds_cli/user.py, dds_cli/utils.py
Added a missed timeout and activated the no_prompt in user deletion too.
=> Add confirmation in case of project deletion

CHANGELOG.md, dds_cli/directory.py
Add in a new custom error message when `--directory` exists, so that it's clearer what is wrong.
Note that these should probably be raising exceptions rather than doing `sys.exit`.. But I'm a bit behind what the current methodology is so I'll leave that for a suggestion / separate PR.
=> Improve error message when --destination exists

CHANGELOG.md, dds_cli/account_manager.py, dds_cli/exceptions.py, dds_cli/utils.py, tests/test_add_user.py
Print out which projects a user could not give access to and the errors. Should be used with https://github.com/ScilifelabDataCentre/dds_web/pull/1045
=> Fix project access error message

CHANGELOG.md, dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/account_manager.py, dds_cli/data_lister.py, dds_cli/utils.py
List the Unit Admins and Unit Personnel within the authenticated users unit. 
**Test with:** https://github.com/ScilifelabDataCentre/dds_web/pull/1050
=> New `dds user ls` command

dds_cli/auth.py
This patch updates the authentication text and switches "LOG.error" to "LOG.info".
Fixes #387.
=> Authentication text

CHANGELOG.md, dds_cli/__main__.py
After discussions with @alneberg I decided to remove the `abort` command and add the `--abort` flag to the `archive` command. The flag is optional and indicates that something has gone wrong. 
=> changed from aborted command to an abort flag in archiving

CHANGELOG.md, dds_cli/user.py
Fix file permissions for token creation on Windows.
The internal check is skipped since it's not compatible with Windows.
To check whether it's correct:
```
icacls .dds_cli_token
```
Should only be one entry: `(your username): (R,W)`
=> Set file permissions using icacls on Windows, no check

dds_cli/__main__.py, dds_cli/data_lister.py, dds_cli/utils.py
Currently the project listing functionality does not display the project sizes, usage and costs like I want them to. 
The default should be to display them in the exact form, not a common unit prefix and not any automatic recognition of the numbers. 
In the future, after getting the DDS into production, we can improve on this and add additional options like @MatthiasZepper has done in https://github.com/ScilifelabDataCentre/dds_cli/pull/377 for example. This however should not change the default that I explained above. 
This PR also fixes the bug where the size is not shown for the Researchusers. 
=> Fix size usage cost 

CHANGELOG.md, dds_cli/data_remover.py
* Add information about number of deleted files for folder deletion
* Warn about the case where the files are deleted in s3 but not in db
=> Add info about number of deleted files, db delete failure

CHANGELOG.md, dds_cli/account_manager.py
This patch adds a message when the project access would be fixed for a user.
Fixes #447.
=> Project Access Fix Message

dds_cli/project_creator.py
Changed to just getting the json response once instead of everytime it's used, removed the unnecessary `else` and the `try`/`except` block at the end of creating project. 
=> Change json response

dds_cli/account_manager.py, dds_cli/utils.py
=> Better error message if there are no unit users

dds_cli/base.py
This patch replaces "requests.get" with the "request_get" function in "utils.py".
Fixes DDS-1236.
=> Replace "requests.get" with the "request_get" function

dds_cli/file_handler_remote.py
This patch replaces "requests.get" in "file_handler_remote.py" with the "request_get" function in "utils.py".
Fixes DDS-1242.
=> Replace "requests.get" in "file_handler_remote.py" with the "request_get" function in "utils.py"

dds_cli/account_manager.py, dds_cli/data_remover.py, dds_cli/utils.py
=> Replace "requests.delete/post" in "account_manager.py" with the "perform_request" function from "utils.py"

CHANGELOG.md, dds_cli/account_manager.py, dds_cli/base.py, dds_cli/data_getter.py, dds_cli/data_lister.py, dds_cli/data_putter.py, dds_cli/data_remover.py, dds_cli/file_handler_local.py, dds_cli/file_handler_remote.py, dds_cli/motd_manager.py, dds_cli/project_creator.py, dds_cli/project_status.py, dds_cli/s3_connector.py, dds_cli/unit_manager.py, dds_cli/user.py, dds_cli/utils.py, tests/test_utils.py
Returns the parsing of the project related `"errors"`, specifically when adding a user to a project you do not have access to (i.e. your project key does not exist). The PR also returns these errors to the underlying functions, which means all calls to `perform_request` are changed by adding an extra returned variable (`_` because unused for most cases). 
Fixes DDS-1265
1. Start up the dds_web
2. Remove all rows in `ProjectUserKeys`
3. Test `dds user add`
a. Invite a new Researcher to project --> Error: `dds user add testemail@mail.com -r Researcher -p project_1`
b. Invite new Unit Personnel --> Error: `dds user add anothertestemail@mail.com -r Unit Personnel`
c. Add existing Unit Personnel to project as Researcher --> Error: `dds user add …
=> Parse project specific errors from API

dds_cli/auth.py, dds_cli/user.py, dds_cli/utils.py, tests/test_utils.py
Cloned https://github.com/ScilifelabDataCentre/dds_cli/pull/495 and changed slightly.
Fixes DDS-1259
=> Version header fix

CHANGELOG.md, dds_cli/user.py
Changed the message from 
> unable to confirm whether file permissions are correct on windows
to 
> Storing the login information locally - please ensure no one else an access the file at
due to previous message confusing the users - sounds like something is wrong but it's only that there is a check regarding the token permissions that cannot be performed on windows.
Fixes DDS-1310
**Tested on Windows.**
=> change message

CHANGELOG.md, dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/account_manager.py, dds_cli/utils.py, tests/test_account_manager.py, tests/test_utils.py
List all users as super admin, and find users if they exist.
=> List all users as superadmin

CHANGELOG.md, dds_cli/__init__.py, dds_cli/__main__.py
To allow us (and possibly users) to test the DDS without having access to the production version, e.g. before signing up or in the case of a new feature, I added the dev instance link and a check for "test-instance". 
Fixes X
=> Link to dev instance added to allow testing 

dds_cli/__init__.py
HTTPConnectionPool - time out. Increased the timeout. Probably need to look at why the connection is taking so long. 
Fixes X 
=> Increased timeout variable to 120 seconds

CHANGELOG.md, dds_cli/base.py
Due to key derivation issue. It currently looks like the DDS freezes. 
Add a message inform users that the DDS is working and that it's not frozen so that they know it can take some time before the download starts
Fixes DDS-1315
=> Add spinner when getting project private

dds_cli/__main__.py
When the dds command is run without any parameters it returned the following:
```
valge939@BMC-3P9KJ2DHP dds_cli % dds     
︵ 
︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
︶  (  ) ) (    https://delivery.scilifelab.se/ 
︶ (  )    Version 1.0.73 
︶
Traceback (most recent call last):
File "/Users/valge939/.pyenv/versions/3.9.13/bin/dds", line 5, in <module>
from dds_cli.__main__ import dds_main
File "/Users/valge939/scilifelab_dc/dds_cli/dds_cli/__main__.py", line 95, in <module>
if sys.argv[1] != "motd":
IndexError: list index out of range
```
=> Fixes an error when dds is run without any parameter

CHANGELOG.md, dds_cli/base.py, dds_cli/data_remover.py
This is an add-on to https://github.com/ScilifelabDataCentre/dds_cli/pull/525 - some refactoring.
Merge 525 first and then rebase this. 
Should be tested with https://github.com/ScilifelabDataCentre/dds_web/pull/1266 
Fixes DDS-1333
=> Set project as busy when starting deletion and not busy when done (3)

CHANGELOG.md, dds_cli/__init__.py, dds_cli/__main__.py, dds_cli/maintenance_manager.py
Add commands `dds maintenance on` and `dds maintenance off` for turning Maintenance mode on and off
works with https://github.com/ScilifelabDataCentre/dds_web/pull/1286
=> Maintenance command for setting maintenance mode

CHANGELOG.md, dds_cli/data_lister.py
New column in project table to display name or creator.
=> Display creator when listing projects

CHANGELOG.md, dds_cli/utils.py
When a requests takes too long, it times out, currently leading to the error message `ERROR Expecting value: line 1 column 1 (char 0)`. This PR catches the timeout exception and prints a more understandable message.
=> Catch Timeout exception

.github/pull_request_template.md, docs/procedures/new_release.md
> **Before submitting the PR**
>
> - Fill in and tick fields
> - _Remove all rows_ that are not relevant for the current PR
>   - Revelant option missing? Add it as an item and add a PR comment informing that the new option should be included into this template.
>
- Tests
=> Update pr template and add release intructions

.github/workflows/release-cli.yml, .github/workflows/test-pypi-cli.yml, CHANGELOG.md
> **Before submitting the PR**
>
> - Fill in and tick fields
> - _Remove all rows_ that are not relevant for the current PR
>   - Revelant option missing? Add it as an item and add a PR comment informing that the new option should be included into this template.
>
In order to debug and prevent potential issues during releases, we should also 1. publish the CLI to TestPyPi on pr to dev and on release before real publishing, 2. make sure that the hashes are correct. Possible that we also should recommend verifying the hashes after installation. 
The `print_hash: true` part in tells the action to show the hashes of what will be published. Easily verified manually by checking on PyPi. If something happens though and there's …
=> Publish to TestPyPi on PR and release 

.github/workflows/snyk-scan-cli.yml, CHANGELOG.md
> **Before submitting the PR**
>
> - Fill in and tick fields
> - _Remove all rows_ that are not relevant for the current PR
>   - Revelant option missing? Add it as an item and add a PR comment informing that the new option should be included into this template.
>
- Fixes an issue in GitHub / Jira:
- Tests
- Trivy:
=> Scan CLI code with snyk

CHANGELOG.md, dds_cli/__main__.py, dds_cli/base.py, dds_cli/exceptions.py
NGI noticed that some files were not uploaded, but the DDS had not returned an error code 1, which meant that they were not aware of any error. This should fix that. 
_X_
- Blocking PRs
- Self review
- Comments, docstrings, etc
- Documentation
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
Run `npx prettier --write .` locally to execute formatting.
- **Yamllint**: Linting of yaml files.
- **Tests**: Pytest to verify that functionality works as expected.
- **TestPyPi**: Build CLI and publish to TestPyPi in …
=> Return exit code 1 if only partial upload

CHANGELOG.md, dds_cli/user.py, dds_cli/utils.py
A user reported that they had used a specific special character in the password and that the CLI was giving a UnicodeEncodeError when trying to log in. Turns out that this is a `requests` issue and has been reported quite a lot, but it'd not something they'll be fixing. 
This snippet is what causes the error: 
https://github.com/psf/requests/blob/7f694b79e114c06fac5ec06019cada5a61e5570f/requests/auth.py#L59-L60 
To avoid this, we're catching the error, and (in the web) adding a check for that the username and password only contain characters that are latin1 encodable.
https://github.com/ScilifelabDataCentre/dds_web/pull/1402
_X_
- Blocking PRs
- …
=> Catch UnicodeEncodeError in case of non-latin 1 chars

.github/pull_request_template.md, CHANGELOG.md, docs/procedures/new_release.md
1. **Description:** Change to the PR template --> this structure. 
2. **Jira task / GitHub issue:** DDS-1501
3. **How to test:** _X_
- Blocking PRs
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
Run `npx prettier --write .` locally to execute formatting.
- **Yamllint**: Linting of yaml files.
- **Tests**: …
=> Restructure PR template and add information to release instructions

.github/pull_request_template.md, docs/procedures/new_release.md
1. **Description:** Since we have changed the changelog to sprintlog, and are now using a CHANGELOG.rst file for version changelogs, we need to include the updating of this file to the release instructions.
2. **Jira task / GitHub issue:** DDS-1504
3. **How to test:** _X_
- Blocking PRs
- **Prettier**: General code formatter. Our use …
=> Update PR template include changelog instructions

SPRINTLOG.md, dds_cli/__main__.py
1. **Description:** Sometimes we get questions regarding the project- and data statistics on the DDS. At the moment we need to run manual queries in the database for this, which we want to avoid as much as possible, so this is a start to a / temporary command which can get the number of projects (either total or active) or check the total amount of data currently stored in the system. I could've listed the units and gotten the size from there, but that'd mean that a part of this command was only usable by Super Admins, and a part by everyone. Used this for code simplicity. 
2. **Jira task / GitHub issue:** DDS-1520
3. **How to test:** Try the stats command.
5. **Add …
=> dds stats 

SPRINTLOG.md, dds_cli/file_encryptor.py, requirements.txt
1. **Description:** Bumping cryptography package due to vulnerability
2. **Jira task / GitHub issue:** https://github.com/ScilifelabDataCentre/dds_cli/security/dependabot/11
- Blocking PRs …
=> Bump cryptography to 41.0.3

SPRINTLOG.md, dds_cli/utils.py
1. **Description:** When there is no json response from the API, the CLI prints out an error that is not understandable. This risks confusing both us and users. Could happen during a timeout for example. This PR updates the error message.  
2. **Jira task / GitHub issue:** DDS-1584
- Blocking PRs
- **Black**: Python code …
=> Return understandable message when response doesn't contain json

.github/workflows/release-cli.yml, SPRINTLOG.md, docs/conf.py, requirements-dev.txt
1. **Description:** The GitHub Actions to generate the documentation wasn't working. The issue was found to be in a problem with the dependencies. The container need certain modules and libraries to be installed. As well as proper modules to convert the svg images.
2. **Jira task / GitHub issue:** https://scilifelab.atlassian.net/browse/DDS-1473
3. **How to test:** Trigger the actions
- Blocking PRs
- **Black**: Python code formatter. Does not …
=> Dds 1473 GitHub Actions not able to generate the documentation

SPRINTLOG.md, dds_cli/__main__.py, dds_cli/base.py, dds_cli/project_info.py, dds_cli/project_status.py, tests/test_project_status.py
1. **Description:** When deleting or achiving a project a message is printed with the project information before asking for confirmation.
2. **Jira task / GitHub issue:** https://scilifelab.atlassian.net/jira/software/projects/DDS/boards/13?selectedIssue=DDS-1401
3. **How to test:** dds_cli project status archive -p project_1 and then you should be able to see the information of the project and a confirmation prompt
- Blocking PRs
- **Black**: …
=> Dds 1401 print project info when deleting archiving project

SPRINTLOG.md, dds_cli/data_getter.py, dds_cli/utils.py, tests/test_utils.py
=> Catch ApiRequestError in update_db 

.github/pull_request_template.md
=> Update PR template to include Security Alert fix details

SPRINTLOG.md, docs/testing.rst
Updating the user-facing documentation for the migration of the Testing instance. 
Also, in a separate commit, removed a sentence that said there was _no_ risk. Can move this commit to its own branch, if preferred. 
DDS-1942
What _type of change(s)_ does the PR contain?
_Check the boxes when the specified checks have passed._
**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](https://github.com/ScilifelabDataCentre/dds_cli/blob/dev/.github/pull_request_template.md).**
=> DDS-1942 update docs for testing migration

.github/workflows/release-cli.yml, SPRINTLOG.md
=> Update MacOs actions image due to broken pipeline

SPRINTLOG.md, docs/installation.rst
=> Update documentation to have correct executable name

SPRINTLOG.md, dds_cli/__init__.py, dds_cli/version.py
=> Added new dev instance url to cli config

SPRINTLOG.md, dds_cli/__main__.py, dds_cli/motd_manager.py, tests/test_motd_manager.py
=> Modify the command dds motd send to allow the option to send only to unit personnel

tests/requirements-test.txt
=> Removing Werkzeug from requirements-test

SPRINTLOG.md, dds_cli/base.py
=> Add 'upload' or 'download' to directory name

.github/pull_request_template.md, SPRINTLOG.md, docs/procedures/new_release.md
For some reason there's duplicated steps in the release procedure.
**Is …
=> Update PR template and remove duplicates in release procedure

dds_cli/data_getter.py
There appear to be many errors in the log related to file corruption and integrity issues, that is before file decryption starts. One cause might be a truncated file that was not completely downloaded. This PR adds some code to verify file size.
=> Corrupt file check - file size check

SPRINTLOG.md, dds_cli/dds_gui/pages/authentication/authentication_form.py, tests/gui_tests/test_authentication.py
**If the target branch is `master`**:
_Describe what the PR changes and why._
- Add error handling for wrong/empty credentials
- Add error handling for wrong/empty 2fa code
- Update tests 
_Link GitHub issue or provide Jira ID._
HMS-2492
_If applicable: How did you verify the change? Include commands, data, or screenshots._
Added additional tests. To test the GUI manually, run `textual run gui_build/gui_standalone.py` and enter "invalid" credentials and 2fa codes.
_Anything that helps reviewers (e.g. areas needing close attention)._
---
Once all boxes are checked, mark the PR as **Ready for Review** and tag at least one team member as the initial reviewer.
=> Fix error handling bug in GUI authentication

.github/workflows/pytest-cli.yml, SPRINTLOG.md
**If the target branch is `master`**:
_Describe what the PR changes and why._
Revert the windows version in the pytest workflow from latest to 2022 to fix failing Textual tests that appeard after the upgrade to using latest. 
_Link GitHub issue or provide Jira ID._
HMS-2540
_If applicable: How did you verify the change? Include commands, data, or screenshots._
_Anything that helps reviewers (e.g. areas needing close attention)._
---
Once all boxes are checked, mark the PR as **Ready for Review** and tag at least one team member as the initial reviewer.
=> Downgrade windows version to 2022
